# Generated by Django 4.2 on 2023-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
