# Generated by Django 4.2 on 2023-04-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_profiles_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='bio',
        ),
    ]
