# Generated by Django 4.2 on 2023-04-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_profiles_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
    ]
