# Generated by Django 4.2 on 2023-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_profiles_group_rename_name_group_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
