# Generated by Django 4.2 on 2023-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(default=1, max_length=221),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroupList',
        ),
    ]
