# Generated by Django 4.2 on 2023-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_group_link_delete_grouplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.ManyToManyField(to='backend.link'),
        ),
    ]
